'use client'
import { useState } from 'react'
import Drawer from '../components/drawer(mob)/Drawer'
import Navbar from '../components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Merrno, best online shop in your town!',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const [drawer, setDrawer] = useState(false)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="select-none h-screen overflow-auto scrollbar-hide relative">
          <Drawer drawer={drawer} setDrawer={setDrawer} />
          <Navbar setDrawer={setDrawer} />
          {/* For holding all children */}
          <div className='relative'>
            {/* div for centering (horizontally) all chilren */}
            <div className='max-w-7xl mx-auto'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
